package com.example.quiz.utilities;

public class Constants {
    public static final String KEY_COLLECTION_USERS = "users";
    public static final String KEY_COLLECTION_QUIZ = "quizs";
    public static final String KEY_COLLECTION_QUESTION = "questionBank";
    public static final String KEY_NAME = "name";
    public static final String PUBLICK = "publick";
    public static final String LIKE = "like";
    public static final String COUNT = "count";
    public static final String FOLLOWERS = "followers";
    public static final String FOLLOWINGS = "followings";
    public static final String PLAY_WITH_FRIEND = "playWithFriend";
    public static final String CREATOR_NAME = "creatorName";
    public static final String PLAY_WITH_FRIEND_ID = "playWithFriendId";
    public static final String USER_IMAGE = "userImage";
    public static final String COUNT_USER = "countUser";
    public static final String NEXT_PLAY = "nextPlay";
    public static final String KEY_EMAIL = "email";
    public static final String DESCRIPTION = "description";
    public static final String TYPE = "type";
    public static final String PLAY = "play";
    public static final String CODE = "code";
    public static final String COUNT_ANSWERED = "countAnswered";
    public static final String COUNT_QUESTION = "countQuestion";
    public static final String TIME = "time";
    public static final String SCORE = "score";
    public static final String POINT = "point";
    public static final String FOLLOWINGS_ID = "followingsId";
    public static final String ANSWER = "answer";
    public static final String ANSWER_TEXT = "answerText";
    public static final String KEY_PREFERENCE_NAME = "chatAppPreference";
    public static final String KEY_IS_SIGNED_IN = "isSignedIn";
    public static final String QUESTION = "question";
    public static final String KEY_USER_ID = "userId";
    public static final String KEY_IMAGE = "image";
    public static final String KEY_FCM_TOKEN = "fcmToken";
    public static final String QUIZ_ID = "quizId";
    public static final String NICK_NAME = "nickName";
    public static final String KEY_USER_PHONE = "phone";
    public static final String QUESTION_ID = "questionId";
    public static final String STATUS = "status";
    public static final String BIRTHDAY = "birthday";
    public static final String EMAIL_DEVELOPER = "uptech.messenger@mail.ru";
}
